user  nginx;
worker_processes  auto;

pid /var/run/nginx.pid;

events {
    worker_connections  4096;
    multi_accept on;
    use epoll;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server_tokens off;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 30;
    keepalive_requests 1000;

    client_body_timeout 15;
    client_header_timeout 15;
    send_timeout 15;

    client_max_body_size 10m;

    large_client_header_buffers 4 16k;

    reset_timedout_connection on;

    log_format prod_security
        '$remote_addr - $remote_user [$time_local] '
        '"$request" $status $body_bytes_sent '
        'host="$host" '
        'ref="$http_referer" '
        'ua="$http_user_agent" '
        'xff="$http_x_forwarded_for" '
        'xri="$http_x_real_ip" '
        'ct="$http_content_type" '
        'cl="$http_content_length" '
        'auth="$http_authorization" '
        'all_headers="$request"';

    access_log /var/log/nginx/access.log prod_security;
    error_log  /var/log/nginx/error.log warn;

    include /etc/nginx/conf.d/*.conf;
}